import {
  BadgeCheck,
  Globe,
  Database,
  Paintbrush,
  Ruler,
  Edit,
  Zap,
  Layers,
  LifeBuoy,
  ShoppingBag,
  Puzzle,
  Lock,
  Palette,
  ShieldCheck,
  Calendar,
  Rocket,
  Handshake,
  Sparkles,
} from "lucide-react";

export const icons = {
  BadgeCheck: BadgeCheck,
  Globe: Globe,
  Database: Database,
  Paintbrush: Paintbrush,
  Ruler: Ruler,
  Edit: Edit,
  Zap: Zap,
  Layers: Layers,
  LifeBuoy: LifeBuoy,
  ShoppingBag: ShoppingBag,
  Puzzle: Puzzle,
  Lock: Lock,
  Palette: Palette,
  ShieldCheck: ShieldCheck,
  Calendar: Calendar,
  Rocket: Rocket,
  Handshake: Handshake,
  Sparkles: Sparkles,
};
